# Generated by Django 4.1 on 2023-01-15 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="info",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "detection_name",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="images")),
                ("video", models.FileField(blank=True, null=True, upload_to="videos")),
            ],
        ),
    ]
