# Generated by Django 4.1 on 2023-01-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detection_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="info",
            old_name="image",
            new_name="image_1",
        ),
        migrations.AddField(
            model_name="info",
            name="image_2",
            field=models.ImageField(blank=True, null=True, upload_to="images"),
        ),
    ]
