# Generated by Django 4.1 on 2023-01-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Quiz", "0002_question_image_question_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="slug",
            field=models.CharField(default="", max_length=130),
        ),
    ]
